#!/usr/bin/env python3
"""Bake a crawlable copy of each page's JS-held copy into its .dc.html source.

The problem this solves
-----------------------
Pages render client-side via support.js, and much of the copy (FAQ answers,
claim types, guides, how-it-works steps) sits inside <script data-dc-script> as
JavaScript data. A crawler that does not execute JS sees {{ placeholders }}, so
those pages read as thin and were not being indexed.

How it works
------------
support.js does `dc.replaceWith(hostEl)` -- it REPLACES the <x-dc> element with
<div id="dc-root">. Anything outside <x-dc> survives that. So we inject the same
copy as plain semantic HTML in <div id="dc-prerender"> just before <x-dc>, and a
small script removes it the moment React has mounted. Same words, so nothing is
hidden from users that is not shown to crawlers. It also doubles as a no-JS
fallback: if unpkg is unreachable the page still shows its content.

Re-run this whenever the copy in a data-dc-script block changes.

Usage:  python3 tools/prerender.py [page ...]   (default: every page with data)
"""
import html
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
EXTRACT = ROOT / "tools" / "extract-content.js"

PAGES = [
    "index", "claim-check", "how-it-works", "our-panel", "claims",
    "success-stories", "blog", "faq", "contact",
]

START = "<!-- dc-prerender:start  generated by tools/prerender.py -->"
END = "<!-- dc-prerender:end -->"

WRAP_STYLE = (
    "max-width:860px;margin:0 auto;padding:40px 24px;"
    "font-family:'Inter',system-ui,sans-serif;color:#0F172A;line-height:1.7"
)
H_STYLE = "font-family:'Spectral',serif;font-size:20px;font-weight:600;margin:28px 0 8px"
P_STYLE = "font-size:16px;color:#334155;margin:0 0 14px"

SWAP_SCRIPT = """<script>
/* Drop the crawlable copy as soon as the React runtime has mounted. */
(function () {
  var pre = document.getElementById('dc-prerender');
  if (!pre) return;
  function drop() {
    var root = document.getElementById('dc-root');
    if (!root || !root.firstChild) return false;
    if (pre.parentNode) pre.parentNode.removeChild(pre);
    return true;
  }
  if (drop()) return;
  var obs = new MutationObserver(function () { if (drop()) obs.disconnect(); });
  obs.observe(document.documentElement, { childList: true, subtree: true });
})();
</script>"""

HEADING_KEYS = ("title", "q", "question", "name", "heading", "category")


def extract(stem):
    out = subprocess.run(
        ["node", str(EXTRACT), str(SITE / f"{stem}.dc.html")],
        capture_output=True, text=True, check=True,
    )
    return json.loads(out.stdout or "null")


def to_html(data, seen):
    """Render the extracted data as plain semantic HTML, skipping repeats."""
    parts = []

    def emit_string(s, heading=False):
        key = s.strip()
        if key in seen:
            return
        seen.add(key)
        tag, style = ("h2", H_STYLE) if heading else ("p", P_STYLE)
        parts.append(f'<{tag} style="{style}">{html.escape(key)}</{tag}>')

    def walk(node):
        if isinstance(node, str):
            emit_string(node)
        elif isinstance(node, list):
            for item in node:
                walk(item)
        elif isinstance(node, dict):
            head = next((k for k in HEADING_KEYS if isinstance(node.get(k), str)), None)
            if head:
                emit_string(node[head], heading=True)
            for k, v in node.items():
                if k != head:
                    walk(v)

    walk(data)
    return "\n".join(parts)


def inject(stem, body):
    path = SITE / f"{stem}.dc.html"
    src = path.read_text(encoding="utf-8")
    src = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?", "", src, flags=re.S)
    if body:
        block = (
            f"{START}\n"
            f'<div id="dc-prerender" style="{WRAP_STYLE}">\n{body}\n</div>\n'
            f"{SWAP_SCRIPT}\n"
            f"{END}\n"
        )
        if "<x-dc>" not in src:
            raise SystemExit(f"{path.name} has no <x-dc> block")
        src = src.replace("<x-dc>", block + "<x-dc>", 1)
    path.write_text(src, encoding="utf-8")


def main():
    for stem in (sys.argv[1:] or PAGES):
        data = extract(stem)
        if not data:
            print(f"{stem:18} no JS-held copy, nothing to bake")
            continue
        body = to_html(data, set())
        inject(stem, body)
        words = len(re.sub(r"<[^>]+>", " ", body).split())
        print(f"{stem:18} +{words:4} crawlable words baked in")


if __name__ == "__main__":
    main()
