#!/usr/bin/env python3
"""Add JSON-LD structured data to the pages that can carry it.

FAQPage on /faq (built from the same data the page renders, so it can never
drift) and Organization on the homepage. Both go in the real <head>, not the
<helmet> block, so a crawler sees them without running JavaScript.

Idempotent: re-running replaces the previous block.

Usage: python3 tools/schema.py
"""
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
BASE = "https://investmentreclaimuk.co.uk"

START = "<!-- dc-schema:start  generated by tools/schema.py -->"
END = "<!-- dc-schema:end -->"


def extract(stem):
    out = subprocess.run(
        ["node", str(ROOT / "tools" / "extract-content.js"), str(SITE / f"{stem}.dc.html")],
        capture_output=True, text=True, check=True,
    )
    return json.loads(out.stdout or "null")


def write(stem, payload):
    path = SITE / f"{stem}.dc.html"
    src = path.read_text(encoding="utf-8")
    src = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?", "", src, flags=re.S)
    block = (
        f"{START}\n"
        f'<script type="application/ld+json">\n'
        f"{json.dumps(payload, indent=1, ensure_ascii=False)}\n"
        f"</script>\n{END}\n"
    )
    src = src.replace("</head>", block + "</head>", 1)
    path.write_text(src, encoding="utf-8")
    print(f"{stem:12} {payload['@type']} schema written")


faqs = extract("faq")["faqs"]
write("faq", {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
        {
            "@type": "Question",
            "name": f["q"],
            "acceptedAnswer": {"@type": "Answer", "text": f["a"]},
        }
        for f in faqs
    ],
})

write("index", {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "Investment Reclaim UK",
    "url": BASE + "/",
    "logo": BASE + "/assets/ir-logo-email.png",
    "email": "info@investmentreclaimuk.co.uk",
    "areaServed": "GB",
    "description": (
        "Investment Reclaim UK is a claims introduction service. We are not a "
        "law firm and do not give legal advice. We review enquiries about "
        "mis-sold investments and pensions and, where appropriate, introduce "
        "people to an SRA-regulated solicitor from a vetted panel."
    ),
    "sameAs": ["https://www.facebook.com/profile.php?id=1381457301708032"],
})
